### ISSUE TITLE
Circles and ellipses do not work with clipperUnite

### ISSUE THREAD

**Issue by blayzen-w** [northamerican/paper-clipper#3]
It looks like circles and ellipses do not work well with clipperUnite and turns them into squares. It seems to work fine with other shapes like stars. I'm not sure if this is an issue with this library or `js-angusj-clipper`.

In the image below, the original circle is red with a black border and the united path is green with a blue border.

<img width="58" alt="paper-clipper-bug" src="https://user-images.githubusercontent.com/31136117/114802442-9190d800-9d52-11eb-8b5f-bbff7c1833da.png">

The following is a quick example of the issue.
```typescript
    let circle = new this.paper.Path.Circle(new this.paper.Point(100, 100), 40);
    circle.fillColor = new this.paper.Color('red');
    circle.strokeColor = new this.paper.Color('black');
    circle.strokeWidth = 2;

    await this.clipper_import;
    const unitedPaths = await clipperUnite(this.clipper)([circle]);

    let merged = unitedPaths[0];
    merged.strokeWidth = 2;
    merged.strokeColor = new this.paper.Color('blue');
    merged.fillColor = new this.paper.Color('green');
```

On a side note this package is awesome! Thanks for putting in the work to create a fast offset and unite path package for paperjs. I've been wanting something like this for years.

**Comment by northamerican** [comment]
@blayzen-w thanks for reporting this issue, glad it's been of use. every solution has fatal flaws thus far and this one is no exception. i really haven't tested this on much more than complex organic shapes (my use case).

if you can supply me with a basic repo or zip where i can reproduce the issue, it would help.

**Comment by blayzen-w** [comment]
Here is boiled down example project
https://github.com/blayzen-w/paper-clipper-issue-3/

I might have some time in a few weeks to look into it more

**Comment by blayzen-w** [comment]
It looks like this is due to the control points on bezier curves being ignored and [only the x, y point are used](https://github.com/northamerican/paper-clipper/blob/master/src/unite.ts#L15). This seems to be a limitation of the `js-angusj-clipper` library and not something that can be fixed.

**Comment by northamerican** [comment]
@blayzen-w in this case, i'd suggest [flatten](http://paperjs.org/reference/path/#flatten)ing the path before outlining. this will redraw your path using straight segments that will be understood by clipper. let me know if that helps.

side note - i intend on refactoring/improving/making optional paper-clipper's built-in betterSimplify function at some point as it can also mess up simple, non-organic shapes.

**Comment by blayzen-w** [comment]
Thanks for the update. That flatten function looks really promising with a low flatness setting. I switched form using a Circle to a RegularPolygon which seemed to do the trick but that flatten function should help me correct some of the other errors that would pop up occasionally from merging complex shapes. The performance so far has been great and I would be interested in trying out that betterSimplify function.

**Comment by northamerican** [comment]
@blayzen-w  good to hear. paper-clipper calls betterSimplify on a path every time to 'restore' bezier curves that get lost in clipper. in some cases, particularly simple inorganic shapes, it over-corrects. #1 would allow it to be disabled optionally.

**Comment by blayzen-w** [comment]
@northamerican I was just noticing that while working on a simple shape. It seem to create a budge where I'm assuming the paths join. I think an option to disable or provide your own simplify function would be a good idea. I would probably go for a lower quality fast implementation due performance constraints with the project I'm working on.

Without betterSimplify
![Screen Shot 2021-05-25 at 3 30 48 PM](https://user-images.githubusercontent.com/31136117/119578376-44504f00-bd71-11eb-94be-cc546b1e10d1.png)

With betterSimplify
![Screen Shot 2021-05-25 at 3 32 00 PM](https://user-images.githubusercontent.com/31136117/119578389-49ad9980-bd71-11eb-96b1-8d1d949b1a1f.png)

**Comment by northamerican** [comment]
@blayzen-w 1.1.0 is released. This should fix the distortion above and allow optional disabling of the built-in simplify function.

**Comment by blayzen-w** [comment]
@northamerican Awesome!
